### ISSUE TITLE
Stack: Interface\AddOns\AstralKeys\Lists\Friends.lua:299: bad argument #3 to 'strformat' (string expected, got nil)

### ISSUE THREAD

**Issue by WiNiFiX** [astralguild/AstralKeys#10]
Message: Interface\AddOns\AstralKeys\Lists\Friends.lua:299: bad argument #3 to 'strformat' (string expected, got nil)
Time: Tue Jan 26 19:24:32 2021
Count: 2
Stack: Interface\AddOns\AstralKeys\Lists\Friends.lua:299: bad argument #3 to 'strformat' (string expected, got nil)
[string "=[C]"]: ?
[string "@Interface\AddOns\AstralKeys\Lists\Friends.lua"]:299: in function <Interface\AddOns\AstralKeys\Lists\Friends.lua:290>
[string "@Interface\AddOns\AstralKeys\Lists\Friends.lua"]:384: in function `method'
[string "@Interface\AddOns\AstralKeys\Communications.lua"]:82: in function <Interface\AddOns\AstralKeys\Communications.lua:70>

Locals: (*temporary) = "%s:%s:%d:%d:%d:%d:%d:%d"
(*temporary) = "Thunklin-Twilight'sHammer"
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = 183
(*temporary) = nil
(*temporary) = 1
(*temporary) = 0
(*temporary) = "string expected, got nil"

**Comment by tsitra** [comment]
I get the same error with nearly the same trace (different character/server). It pops up frequently to the point that I've had to disable lua error reporting in WoW just to be able to play.

Additionally, when looting any chest from the end of the M+ run, it announces my key as though it just discovered that I have one.

**Comment by tsitra** [comment]
Update to my previous comment: When I joined a guild, the error seems to have disappeared.

**Comment by sinfonianartist** [comment]
What this looks like is that AstralKeys can't find unit information on your friend, this may be an issue with connected realms. Further investigation is needed.

**Comment by tsitra** [comment]
More information: When I joined a guild, the error stopped appearing.

I play on Bloodhoof, which has a connected realm of Duskwood.

**Comment by sinfonianartist** [comment]
Yeah I am going to spend some time today trying to dig into it. Do you play on a connected realm by chance?

**Comment by tehmilcho** [comment]
hi there i got 3 Chars on Teldrassil and get just by one of them the same Error.
The Error appears on every login by this Char and also in the Addon it says this Chars has no key although he has one.

`Message: Interface\AddOns\AstralKeys\Lists\Friends.lua:299: bad argument #3 to 'strformat' (string expected, got nil)
Time: Sun Mar 28 13:24:37 2021
Count: 1
Stack: Interface\AddOns\AstralKeys\Lists\Friends.lua:299: bad argument #3 to 'strformat' (string expected, got nil)
[string "=[C]"]: ?
[string "@Interface\AddOns\AstralKeys\Lists\Friends.lua"]:299: in function <Interface\AddOns\AstralKeys\Lists\Friends.lua:290>
[string "@Interface\AddOns\AstralKeys\Lists\Friends.lua"]:384: in function `method'
[string "@Interface\AddOns\AstralKeys\Communications.lua"]:82: in function <Interface\AddOns\AstralKeys\Communications.lua:70>

Locals: (*temporary) = "%s:%s:%d:%d:%d:%d:%d:%d"
(*temporary) = "Vollmilcho-Teldrassil"
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = 192
(*temporary) = nil
(*temporary) = 0
(*temporary) = 2
(*temporary) = "string expected, got nil"
`

**Comment by tsitra** [comment]
Looks like this issue can be closed, re: https://github.com/astralguild/AstralKeys/pull/17
