### ISSUE TITLE
Error: bad text keystone

### ISSUE THREAD

**Issue by MarkElf** [astralguild/AstralKeys#101]
Hey, when a guildie used !keys, only my key has been saying bad text keystone. My key stone is a freehold 20.
See image here: https://prnt.sc/0G3_9J352rUf

I'm not seeing a specific error with bugsack.
Version 3.85

**Comment by Xadrakan** [comment]
Same error here. Reverting to version 3.84 solved the issue.

**Comment by AlexSafatli** [comment]
Is your keystone in `/ak` the same keystone that's being shown when they type `'!keys`?

**Comment by Xadrakan** [comment]
Yes, the key displayed is correct despite the BAD TEXT.

**Comment by MarkElf** [comment]
Yes, the key shows up in /ak.

Maybe the issue is it thinks I'm on a different server? My character is on Zul'jin but I see Area-52 on the bottom, if that's even relevant.

**Comment by Xadrakan** [comment]
> Yes, the key shows up in /ak. https://prnt.sc/pD6-czp385Eu
> 
> Maybe the issue is it thinks I'm on a different server? My character is on Zul'jin but I see Area-52 on the bottom, if that's even relevant.

I believe the Area-52 text refers to the author of the Addon.

**Comment by AlexSafatli** [comment]
Can you let me know if the recent version has fixed the issue please?

**Comment by MarkElf** [comment]
Updated and it's fixed. Thank you!
