### ISSUE TITLE
Errors with recent version. (4.06)

### ISSUE THREAD

**Issue by gotex007** [astralguild/AstralKeys#120]
1x AstralKeys/AstralKeys.lua:156: attempt to call field 'AddUnitToSortTable' (a nil value)
[string "@AstralKeys/AstralKeys.lua"]:156: in function `method'
[string "@AstralKeys/Events.lua"]:82: in function <AstralKeys/Events.lua:78>

Locals:
major = "4"
minor = "06"
region = 1
currentTime = 1715564720
d = <table> {
 hour = 21
 min = 45
 wday = 1
 day = 12
 month = 5
 year = 2024
 sec = 20
 yday = 133
 isdst = true
}
hourOffset = -5
(for index) = 1
(for limit) = 86
(for step) = 1
i = 1
(*temporary) = nil
(*temporary) = "Janisdgaf-Stormrage"
(*temporary) = nil
(*temporary) = "DEMONHUNTER"
(*temporary) = 0
(*temporary) = 401
(*temporary) = 2
(*temporary) = 0
(*temporary) = "attempt to call field 'AddUnitToSortTable' (a nil value)"
addon = <table> {
 GetCharacterID = <function> defined @AstralKeys/Character Info.lua:33
 MYTHICKEY_REROLL_NPCID = 197915
 Unit = <function> defined @AstralKeys/Unit Information.lua:22
 modules = <table> {
 }
 WeekTime = <function> defined @AstralKeys/AstralKeys.lua:14
 UnitClass = <function> defined @AstralKeys/Unit Information.lua:45
 AddUnitToList = <function> defined @AstralKeys/Lists/Lists.lua:93
 AddEscHandler = <function> defined @AstralKeys/Frame Functions.lua:250
 SetDefaultModulePrototype = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:405
 AffixThree = <function> defined @AstralKeys/Affixes.lua:167
 UpdateCharacterBest = <function> defined @AstralKeys/Keystone.lua:163
 SetUIScale = <function> defined @AstralKeys/Init.lua:9
 AffixTwo = <function> defined @AstralKeys/Affixes.lua:155
 SetCharacterID = <function> defined @AstralKeys/Character Info.lua:7
 GetCharacterKeyLevel = <function> defined @AstralKeys/Character Info.lua:131
 CreateDropDownFrame = <function> defined @AstralKeys/Frame Functions.lua:96
 WipeUnitList = <function> defined @AstralKeys/Unit Information.lua:39
 AffixOne = <function> defined @AstralKeys/Affixes.lua:142
 EXPANSION_LEVEL = 70
 SetEnabledState = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:420
 GetListFunction = <function> defined @AstralKeys/Lists.lua:24
 UnitMapID = <function> defined @AstralKeys/Unit Information.lua:55
 UnitWeeklyBest = <function> defined @AstralKeys/Unit Information.lua:60
 DoesUnitBelongToList = <function> defined @AstralKeys/Lists/Lists.lua:131
 DataResetTime = <function> defined @AstralKeys/Settings.lua:6
 handleRegionReset = <function> defined @AstralKeys/AstralKeys.lua:63
 OnInitialize = <function> defined @AstralKeys/MinimapButton.lua:25
 NewModule = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:231
 AddListSort = <function> defined @AstralKeys/Tables.lua:177
 TIMEWALKINGKEY_ITEMID = 187786
 GetName = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:275
 RemoveUnitFromList = <function> defined @AstralKeys/Lists/Lists.lua:115
 WipeFriendList = <function> defined @AstralKeys/Lists/Friends.lua:88
 SetPlayerRealm = <function> defined @AstralKeys/Character Info.lua:92
 CreateKeyLink = <function> defined @AstralKeys/Keystone.lua:53
 Disable = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:310
 BNFriendUpdate = <function> defined @AstralKeys/Lists/Friends.lua:31
 Print = <function> defined @DataStore/libs/AceConsole-3.0/AceConsole-3.0.lua:50
 DisplayForcesCountInTooltip = <function> defined @AstralKeys/Forces.lua:3
 L = <table> {
 }
 PushKeyDataToFriends = <function> defined @AstralKeys/Lists/Friends.lua:294
 GuildMemberOnline = <function> defined @AstralKeys/Lists/Guild.lua:27
 MYTHICKEY_CITY_NPCID = 197711
 CheckGuildVersion = <function> defined @AstralKeys/Communications.lua:237
 GetCharacterBestMap = <function> defined @AstralKeys/Char

**Comment by gotex007** [comment]
1x AstralKeys/Frame.lua:335: bad argument #1 to 'SetJustifyH' (Usage: self:SetJustifyH(justifyH))
[string "=[C]"]: in function `SetJustifyH'
[string "@AstralKeys/Frame.lua"]:335: in main chunk

Locals:
(*temporary) = AstralKeyFrameListHelperText {
 0 = <userdata>
}
(*temporary) = "MIDDLE"

**Comment by gotex007** [comment]
1x AstralKeys/Keystone.lua:33: attempt to call field 'UpdateCharacterFrames' (a nil value)
[string "@AstralKeys/Keystone.lua"]:33: in function `method'
[string "@AstralKeys/Events.lua"]:82: in function <AstralKeys/Events.lua:78>

Locals:
characterID = 5
characterWeeklyBest = 0
(*temporary) = nil
(*temporary) = "attempt to call field 'UpdateCharacterFrames' (a nil value)"
addon = <table> {
 GetCharacterID = <function> defined @AstralKeys/Character Info.lua:33
 MYTHICKEY_REROLL_NPCID = 197915
 Unit = <function> defined @AstralKeys/Unit Information.lua:22
 modules = <table> {
 }
 WeekTime = <function> defined @AstralKeys/AstralKeys.lua:14
 UnitClass = <function> defined @AstralKeys/Unit Information.lua:45
 AddUnitToList = <function> defined @AstralKeys/Lists/Lists.lua:93
 AddEscHandler = <function> defined @AstralKeys/Frame Functions.lua:250
 SetDefaultModulePrototype = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:405
 AffixThree = <function> defined @AstralKeys/Affixes.lua:167
 UpdateCharacterBest = <function> defined @AstralKeys/Keystone.lua:163
 SetUIScale = <function> defined @AstralKeys/Init.lua:9
 AffixTwo = <function> defined @AstralKeys/Affixes.lua:155
 SetCharacterID = <function> defined @AstralKeys/Character Info.lua:7
 GetCharacterKeyLevel = <function> defined @AstralKeys/Character Info.lua:131
 CreateDropDownFrame = <function> defined @AstralKeys/Frame Functions.lua:96
 WipeUnitList = <function> defined @AstralKeys/Unit Information.lua:39
 AffixOne = <function> defined @AstralKeys/Affixes.lua:142
 EXPANSION_LEVEL = 70
 SetEnabledState = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:420
 GetListFunction = <function> defined @AstralKeys/Lists.lua:24
 UnitMapID = <function> defined @AstralKeys/Unit Information.lua:55
 UnitWeeklyBest = <function> defined @AstralKeys/Unit Information.lua:60
 DoesUnitBelongToList = <function> defined @AstralKeys/Lists/Lists.lua:131
 DataResetTime = <function> defined @AstralKeys/Settings.lua:6
 handleRegionReset = <function> defined @AstralKeys/AstralKeys.lua:63
 OnInitialize = <function> defined @AstralKeys/MinimapButton.lua:25
 NewModule = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:231
 AddListSort = <function> defined @AstralKeys/Tables.lua:177
 TIMEWALKINGKEY_ITEMID = 187786
 GetName = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:275
 RemoveUnitFromList = <function> defined @AstralKeys/Lists/Lists.lua:115
 WipeFriendList = <function> defined @AstralKeys/Lists/Friends.lua:88
 SetPlayerRealm = <function> defined @AstralKeys/Character Info.lua:92
 CreateKeyLink = <function> defined @AstralKeys/Keystone.lua:53
 Disable = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:310
 BNFriendUpdate = <function> defined @AstralKeys/Lists/Friends.lua:31
 Print = <function> defined @DataStore/libs/AceConsole-3.0/AceConsole-3.0.lua:50
 DisplayForcesCountInTooltip = <function> defined @AstralKeys/Forces.lua:3
 L = <table> {
 }
 PushKeyDataToFriends = <function> defined @AstralKeys/Lists/Friends.lua:294
 GuildMemberOnline = <function> defined @AstralKeys/Lists/Guild.lua:27
 MYTHICKEY_CITY_NPCID = 197711
 CheckGuildVersion = <function> defined @AstralKeys/Communications.lua:237
 GetCharacterBestMap = <function> defined @AstralKeys/Character Info.lua:60
 SetDefaultModuleLibraries = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:363
 TimewaklingAffixThree = <function> defined @AstralKeys/Affixes.lua:195
 PushKeystone = <function> defined @AstralKeys/Keystone.lua:106
 EnableModule = <function> defined @Data

**Comment by gotex007** [comment]
24x AstralKeys/Lists/Guild.lua:150: attempt to call field 'AddUnitToSortTable' (a nil value)
[string "@AstralKeys/Lists/Guild.lua"]:150: in function `method'
[string "@AstralKeys/Communications.lua"]:82: in function <AstralKeys/Communications.lua:70>

Locals:
entry = "Radiantforce-Stormrage:PRIEST:406:6:6:355:469812_Hotmully-Stormrage:DRUID:403:5:2:355:128752_Vintotem-Stormrage:SHAMAN:400:7:7:355:48241_Cruncho-Stormrage:PALADIN:405:7:9:355:4_Thewrongtree-Stormrage:DRUID:400:10:9:355:3_Løap-Stormrage:MONK:399:9:8"
unit = "Radiantforce-Stormrage"
class = "PRIEST"
dungeonID = 406
keyLevel = 6
weekly_best = 6
week = 355
timeStamp = 4
_pos = 50
id = nil
(*temporary) = nil
(*temporary) = "Radiantforce-Stormrage"
(*temporary) = nil
(*temporary) = "PRIEST"
(*temporary) = 0
(*temporary) = 406
(*temporary) = 6
(*temporary) = 6
(*temporary) = "GUILD"
(*temporary) = "attempt to call field 'AddUnitToSortTable' (a nil value)"
find = <function> defined =[C]:-1
addon = <table> {
 GetCharacterID = <function> defined @AstralKeys/Character Info.lua:33
 MYTHICKEY_REROLL_NPCID = 197915
 Unit = <function> defined @AstralKeys/Unit Information.lua:22
 modules = <table> {
 }
 WeekTime = <function> defined @AstralKeys/AstralKeys.lua:14
 UnitClass = <function> defined @AstralKeys/Unit Information.lua:45
 AddUnitToList = <function> defined @AstralKeys/Lists/Lists.lua:93
 AddEscHandler = <function> defined @AstralKeys/Frame Functions.lua:250
 SetDefaultModulePrototype = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:405
 AffixThree = <function> defined @AstralKeys/Affixes.lua:167
 UpdateCharacterBest = <function> defined @AstralKeys/Keystone.lua:163
 SetUIScale = <function> defined @AstralKeys/Init.lua:9
 AffixTwo = <function> defined @AstralKeys/Affixes.lua:155
 SetCharacterID = <function> defined @AstralKeys/Character Info.lua:7
 GetCharacterKeyLevel = <function> defined @AstralKeys/Character Info.lua:131
 CreateDropDownFrame = <function> defined @AstralKeys/Frame Functions.lua:96
 WipeUnitList = <function> defined @AstralKeys/Unit Information.lua:39
 AffixOne = <function> defined @AstralKeys/Affixes.lua:142
 EXPANSION_LEVEL = 70
 SetEnabledState = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:420
 GetListFunction = <function> defined @AstralKeys/Lists.lua:24
 UnitMapID = <function> defined @AstralKeys/Unit Information.lua:55
 UnitWeeklyBest = <function> defined @AstralKeys/Unit Information.lua:60
 DoesUnitBelongToList = <function> defined @AstralKeys/Lists/Lists.lua:131
 DataResetTime = <function> defined @AstralKeys/Settings.lua:6
 handleRegionReset = <function> defined @AstralKeys/AstralKeys.lua:63
 OnInitialize = <function> defined @AstralKeys/MinimapButton.lua:25
 NewModule = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:231
 AddListSort = <function> defined @AstralKeys/Tables.lua:177
 TIMEWALKINGKEY_ITEMID = 187786
 GetName = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:275
 RemoveUnitFromList = <function> defined @AstralKeys/Lists/Lists.lua:115
 WipeFriendList = <function> defined @AstralKeys/Lists/Friends.lua:88
 SetPlayerRealm = <function> defined @AstralKeys/Character Info.lua:92
 CreateKeyLink = <function> defined @AstralKeys/Keystone.lua:53
 Disable = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:310
 BNFriendUpdate = <function> defined @AstralKeys/Lists/Friends.lua:31
 Print = <function> defined @DataStore/libs/AceConsole-3.0/AceConsole-3.0.lua:50
 DisplayForcesCountInTooltip = <function> defined @AstralKeys/Forces.lua:3
 L = <table> {
 }
 PushKeyDataToFriends = <function> defined @AstralKeys/Lists/Friends.lua:294
 GuildMemberOnline = <function> defined @AstralKeys/Lists/Guild.

**Comment by gotex007** [comment]
5x AstralKeys/Lists/Friends.lua:238: attempt to call field 'AddUnitToSortTable' (a nil value)
[string "@AstralKeys/Lists/Friends.lua"]:238: in function `method'
[string "@AstralKeys/Communications.lua"]:82: in function <AstralKeys/Communications.lua:70>

Locals:
entry = "Thewrongtree-Stormrage:DRUID:400:10:355:0:0:9_Papadefensìv-Stormrage:WARRIOR:401:3:355:0:0:8_"
sender = 47
btag = "Rabbit#1215"
unit = "Thewrongtree-Stormrage"
class = "DRUID"
dungeonID = 400
keyLevel = 10
week = 355
timeStamp = 0
_pos = 47
id = 88
(*temporary) = nil
(*temporary) = "Thewrongtree-Stormrage"
(*temporary) = "Rabbit#1215"
(*temporary) = "DRUID"
(*temporary) = "0"
(*temporary) = 400
(*temporary) = 10
(*temporary) = 9
(*temporary) = "FRIENDS"
(*temporary) = "attempt to call field 'AddUnitToSortTable' (a nil value)"
BNET_GAID_TO_BATTLETAG = <table> {
 31 = "Ariaye#1211"
 38 = "Pnash#11747"
 46 = "Rabbit#1215"
 54 = "jcb100#1450"
 62 = "Katina#1627"
 39 = "Melchman30#1179"
 47 = "Rabbit#1215"
 55 = "Valkry#1576"
 63 = "Ddiep#1577"
 32 = "Ariaye#1211"
 40 = "Ellusia#1444"
 48 = "Rabbit#1215"
 56 = "ElCruncho#1139"
 64 = "Skotono#1558"
 33 = "InsaneAngel#11630"
 41 = "Ellusia#1444"
 49 = "Relaksen#1278"
 57 = "ElCruncho#1139"
 66 = "Skotono#1558"
 29 = "Mogar#11903"
 67 = "Katina#1627"
 42 = "Ellusia#1444"
 50 = "Relaksen#1278"
 58 = "ElCruncho#1139"
 69 = "InsaneAngel#11630"
 43 = "Dinner#1185"
 51 = "Relaksen#1278"
 70 = "InsaneAngel#11630"
 30 = "Ariaye#1211"
 36 = "Pnash#11747"
 44 = "BasedPawg#1473"
 52 = "Xyrixas#1534"
 72 = "Masonite#11208"
 71 = "Muddflapp#1666"
 34 = "Muddflapp#1666"
 73 = "Masonite#11208"
 45 = "TheJan1tor#1838"
 53 = "Xyrixas#1534"
 65 = "Skotono#1558"
 74 = "Masonite#11208"
 35 = "Burntlettuce#1968"
 37 = "Pnash#11747"
}
find = <function> defined =[C]:-1
addon = <table> {
 GetCharacterID = <function> defined @AstralKeys/Character Info.lua:33
 MYTHICKEY_REROLL_NPCID = 197915
 Unit = <function> defined @AstralKeys/Unit Information.lua:22
 modules = <table> {
 }
 WeekTime = <function> defined @AstralKeys/AstralKeys.lua:14
 UnitClass = <function> defined @AstralKeys/Unit Information.lua:45
 AddUnitToList = <function> defined @AstralKeys/Lists/Lists.lua:93
 AddEscHandler = <function> defined @AstralKeys/Frame Functions.lua:250
 SetDefaultModulePrototype = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:405
 AffixThree = <function> defined @AstralKeys/Affixes.lua:167
 UpdateCharacterBest = <function> defined @AstralKeys/Keystone.lua:163
 SetUIScale = <function> defined @AstralKeys/Init.lua:9
 AffixTwo = <function> defined @AstralKeys/Affixes.lua:155
 SetCharacterID = <function> defined @AstralKeys/Character Info.lua:7
 GetCharacterKeyLevel = <function> defined @AstralKeys/Character Info.lua:131
 CreateDropDownFrame = <function> defined @AstralKeys/Frame Functions.lua:96
 WipeUnitList = <function> defined @AstralKeys/Unit Information.lua:39
 AffixOne = <function> defined @AstralKeys/Affixes.lua:142
 EXPANSION_LEVEL = 70
 SetEnabledState = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:420
 GetListFunction = <function> defined @AstralKeys/Lists.lua:24
 UnitMapID = <function> defined @AstralKeys/Unit Information.lua:55
 UnitWeeklyBest = <function> defined @AstralKeys/Unit Information.lua:60
 DoesUnitBelongToList = <function> defined @AstralKeys/Lists/Lists.lua:131
 DataResetTime = <function> defined @AstralKeys/Settings.lua:6
 handleRegionReset = <function> defined @AstralKeys/AstralKeys.lua:63
 OnInitialize = <function> defined @AstralKeys/MinimapButton.lua:25
 NewModule = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:231
 AddListSort = <function> defined @AstralKeys/Tables.lua:177
 TIMEWALKINGKEY_ITEMID = 187786
 GetName = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:275
 RemoveUnitFromList = <function> defined @AstralKeys/Lists/Lists.lua:115

**Comment by gotex007** [comment]
9x AstralKeys/Lists/Guild.lua:17: attempt to call field 'UpdateFrames' (a nil value)
[string "@AstralKeys/Lists/Guild.lua"]:17: in function `method'
[string "@AstralKeys/Events.lua"]:82: in function <AstralKeys/Events.lua:78>

Locals:
(*temporary) = nil
(*temporary) = "attempt to call field 'UpdateFrames' (a nil value)"
GUILD_LIST = <table> {
}
addon = <table> {
 GetCharacterID = <function> defined @AstralKeys/Character Info.lua:33
 MYTHICKEY_REROLL_NPCID = 197915
 Unit = <function> defined @AstralKeys/Unit Information.lua:22
 modules = <table> {
 }
 WeekTime = <function> defined @AstralKeys/AstralKeys.lua:14
 UnitClass = <function> defined @AstralKeys/Unit Information.lua:45
 AddUnitToList = <function> defined @AstralKeys/Lists/Lists.lua:93
 AddEscHandler = <function> defined @AstralKeys/Frame Functions.lua:250
 SetDefaultModulePrototype = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:405
 AffixThree = <function> defined @AstralKeys/Affixes.lua:167
 UpdateCharacterBest = <function> defined @AstralKeys/Keystone.lua:163
 SetUIScale = <function> defined @AstralKeys/Init.lua:9
 AffixTwo = <function> defined @AstralKeys/Affixes.lua:155
 SetCharacterID = <function> defined @AstralKeys/Character Info.lua:7
 GetCharacterKeyLevel = <function> defined @AstralKeys/Character Info.lua:131
 CreateDropDownFrame = <function> defined @AstralKeys/Frame Functions.lua:96
 WipeUnitList = <function> defined @AstralKeys/Unit Information.lua:39
 AffixOne = <function> defined @AstralKeys/Affixes.lua:142
 EXPANSION_LEVEL = 70
 SetEnabledState = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:420
 GetListFunction = <function> defined @AstralKeys/Lists.lua:24
 UnitMapID = <function> defined @AstralKeys/Unit Information.lua:55
 UnitWeeklyBest = <function> defined @AstralKeys/Unit Information.lua:60
 DoesUnitBelongToList = <function> defined @AstralKeys/Lists/Lists.lua:131
 DataResetTime = <function> defined @AstralKeys/Settings.lua:6
 handleRegionReset = <function> defined @AstralKeys/AstralKeys.lua:63
 OnInitialize = <function> defined @AstralKeys/MinimapButton.lua:25
 NewModule = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:231
 AddListSort = <function> defined @AstralKeys/Tables.lua:177
 TIMEWALKINGKEY_ITEMID = 187786
 GetName = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:275
 RemoveUnitFromList = <function> defined @AstralKeys/Lists/Lists.lua:115
 WipeFriendList = <function> defined @AstralKeys/Lists/Friends.lua:88
 SetPlayerRealm = <function> defined @AstralKeys/Character Info.lua:92
 CreateKeyLink = <function> defined @AstralKeys/Keystone.lua:53
 Disable = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:310
 BNFriendUpdate = <function> defined @AstralKeys/Lists/Friends.lua:31
 Print = <function> defined @DataStore/libs/AceConsole-3.0/AceConsole-3.0.lua:50
 DisplayForcesCountInTooltip = <function> defined @AstralKeys/Forces.lua:3
 L = <table> {
 }
 PushKeyDataToFriends = <function> defined @AstralKeys/Lists/Friends.lua:294
 GuildMemberOnline = <function> defined @AstralKeys/Lists/Guild.lua:27
 MYTHICKEY_CITY_NPCID = 197711
 CheckGuildVersion = <function> defined @AstralKeys/Communications.lua:237
 GetCharacterBestMap = <function> defined @AstralKeys/Character Info.lua:60
 SetDefaultModuleLibraries = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:363
 TimewaklingAffixThree = <function> defined @AstralKeys/Affixes.lua:195
 PushKeystone = <function> defined @AstralKeys/Keystone.lua:106
 EnableModule = <function> defined @DataStore/libs/AceAddon-3.0/

**Comment by gotex007** [comment]
1x AstralKeys/Lists/Guild.lua:164: attempt to call field 'UpdateFrames' (a nil value)
[string "@AstralKeys/Lists/Guild.lua"]:164: in function `method'
[string "@AstralKeys/Communications.lua"]:82: in function <AstralKeys/Communications.lua:70>

Locals:
weekly_best = "8"
sender = "Papadefensìv-Stormrage"
id = 109
(*temporary) = nil
(*temporary) = "attempt to call field 'UpdateFrames' (a nil value)"
addon = <table> {
 GetCharacterID = <function> defined @AstralKeys/Character Info.lua:33
 MYTHICKEY_REROLL_NPCID = 197915
 Unit = <function> defined @AstralKeys/Unit Information.lua:22
 modules = <table> {
 }
 WeekTime = <function> defined @AstralKeys/AstralKeys.lua:14
 UnitClass = <function> defined @AstralKeys/Unit Information.lua:45
 AddUnitToList = <function> defined @AstralKeys/Lists/Lists.lua:93
 AddEscHandler = <function> defined @AstralKeys/Frame Functions.lua:250
 SetDefaultModulePrototype = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:405
 AffixThree = <function> defined @AstralKeys/Affixes.lua:167
 UpdateCharacterBest = <function> defined @AstralKeys/Keystone.lua:163
 SetUIScale = <function> defined @AstralKeys/Init.lua:9
 AffixTwo = <function> defined @AstralKeys/Affixes.lua:155
 SetCharacterID = <function> defined @AstralKeys/Character Info.lua:7
 GetCharacterKeyLevel = <function> defined @AstralKeys/Character Info.lua:131
 CreateDropDownFrame = <function> defined @AstralKeys/Frame Functions.lua:96
 WipeUnitList = <function> defined @AstralKeys/Unit Information.lua:39
 AffixOne = <function> defined @AstralKeys/Affixes.lua:142
 EXPANSION_LEVEL = 70
 SetEnabledState = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:420
 GetListFunction = <function> defined @AstralKeys/Lists.lua:24
 UnitMapID = <function> defined @AstralKeys/Unit Information.lua:55
 UnitWeeklyBest = <function> defined @AstralKeys/Unit Information.lua:60
 DoesUnitBelongToList = <function> defined @AstralKeys/Lists/Lists.lua:131
 DataResetTime = <function> defined @AstralKeys/Settings.lua:6
 handleRegionReset = <function> defined @AstralKeys/AstralKeys.lua:63
 OnInitialize = <function> defined @AstralKeys/MinimapButton.lua:25
 NewModule = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:231
 AddListSort = <function> defined @AstralKeys/Tables.lua:177
 TIMEWALKINGKEY_ITEMID = 187786
 GetName = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:275
 RemoveUnitFromList = <function> defined @AstralKeys/Lists/Lists.lua:115
 WipeFriendList = <function> defined @AstralKeys/Lists/Friends.lua:88
 SetPlayerRealm = <function> defined @AstralKeys/Character Info.lua:92
 CreateKeyLink = <function> defined @AstralKeys/Keystone.lua:53
 Disable = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:310
 BNFriendUpdate = <function> defined @AstralKeys/Lists/Friends.lua:31
 Print = <function> defined @DataStore/libs/AceConsole-3.0/AceConsole-3.0.lua:50
 DisplayForcesCountInTooltip = <function> defined @AstralKeys/Forces.lua:3
 L = <table> {
 }
 PushKeyDataToFriends = <function> defined @AstralKeys/Lists/Friends.lua:294
 GuildMemberOnline = <function> defined @AstralKeys/Lists/Guild.lua:27
 MYTHICKEY_CITY_NPCID = 197711
 CheckGuildVersion = <function> defined @AstralKeys/Communications.lua:237
 GetCharacterBestMap = <function> defined @AstralKeys/Character Info.lua:60
 SetDefaultModuleLibraries = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:363
 TimewaklingAffixThree = <function> defined @AstralKeys/Affixes.lua:195
 PushKeystone = <function> defined @AstralKeys/Keystone.lua:106
 EnableModule = <function> defined @Interfac

**Comment by Kyylier** [comment]
Thanks for the bug report! 

How frequently are these errors appearing for you? When do they happen (upon login?)

**Comment by gotex007** [comment]
Most of them happened on login and the others were just happening all the time when I'd open friends list and stuff, I'm not really sure.

**Comment by gotex007** [comment]
Seems fixed with the latest release. (4.09)
