### ISSUE TITLE
New deDE.lua breaks translation

### ISSUE THREAD

**Issue by AmonFlorian** [astralguild/AstralKeys#14]
As the new deDE.lua seems to not have been tested and poorly translated attached is a corrected (and to the latest strings updated) version of the file.
Remember: not quoting foreign characters and spaces spits out errors.

```
local L = select(2, ...)[2]('deDE')

-- Default tab names
L['GUILD'] = 'GILDE'
L['FRIENDS'] = 'FREUNDE'
L['PARTY'] = 'GRUPPE'
L['RAID'] = 'RAID'

-- Column Headers
L['LEVEL'] = 'STUFE'
L['DUNGEON'] = 'DUNGEONS'
L['CHARACTER'] = 'CHARAKTER'

-- Subsection Headers
L['CHARACTERS'] = 'CHARAKTERE'
L['AFFIXES'] = 'AFFIXE'

-- Character Labels
L['CURRENT_KEY'] = 'AKTUELL'
L['WEEKLY_BEST'] = 'WÖCH. BESTER'

L['CHARACTER_DUNGEON_NOT_RAN'] = 'Kein Mythisch+ abgeschlossen'
L['CHARACTER_KEY_NOT_FOUND'] = 'Kein Schlüssel gefunden'


-- Dropdown menu selections
L['REPORT_TO'] = 'Melden an'
L['Whisper'] = 'Anflüstern'
L['INVITE'] = 'Einladen'
L['SUGGEST_INVITE'] = "Einladung vorschlagen"
L['REQUEST_INVITE'] = "Einladung anfragen"
L['CANCEL'] = 'ABBRECHEN'
L['NEW_LIST_DESCRIPTION'] = 'Neuer Listenname'
L['CREATE_NEW_LIST'] = 'Neue Liste erstellen'
L['REMOVE_UNIT_FROM_LIST'] = 'Von Liste entfernen'
L['ADD_TO_LIST'] = 'Zur Liste hinzufügen'
L['ADD_REMOVE_LIST'] = 'Liste hinzufügen oder löschen'
L['DELETE_LIST'] = 'Liste löschen'
L['LIST_ADD_HELPER_TEXT'] = 'Jemanden durch Rechtsklick in der GILDEN- oder FREUNDESLISTE hinzufügen'
L['OKAY'] = OKAY

-- Announce messages
L['ANNOUNCE_NEW_KEY'] = 'Astral Keys: Neuer Schlüssel %s'
L['NO_KEY'] = 'Kein Schlüssel'
L['KEYS_RESPOND_ON_NO_KEY'] = 'Ohne eigenen Schlüssel reagieren'


-- Search field texts
L['FILTER_TEXT_DUNGEON'] = 'Sortierung nach Dungeon'
L['FILTER_TEXT_CHARACTER'] = 'Sortierung nach Charakternamen'

-- Options
L['!KEYS_DESC'] = 'In folgenden Chatkanälen auf !keys Befehl reagieren'
L['EXPANDED_TOOLTIP'] = 'Zeige Affix-Beschreibungen im Tooltip'
```

**Comment by AmonFlorian** [comment]
Oh - is there any info if keystone responses are fixed for German clients?
Hasn't worked yet and guild members use ElvUI/WeakAura/etc. to post saved info as AstralKeys is malfunctioning.

**Comment by sinfonianartist** [comment]
Which keystone response in particular? Are you talking based on the !keys input?

**Comment by sinfonianartist** [comment]
This has been merged, and released.

**Comment by AmonFlorian** [comment]
> Which keystone response in particular? Are you talking based on the !keys input?

Exactly. It seems to bug out when trying to format strings in a German environment.
We tested along in a group and affixes went crazy - we even had to change the strformat to get a hoverable tooltip at all.
This was mentioned on curseforge comments as well (change is in 'Key Information.lua':62 -> [...]|h[Keystone:[...] to [...]|h[Schlüsselstein:[...]). Didn't test it any further to check "internationalisation" though.

**Comment by Elehiggle** [comment]
> 
> 
> Oh - is there any info if keystone responses are fixed for German clients?
> Hasn't worked yet and guild members use ElvUI/WeakAura/etc. to post saved info as AstralKeys is malfunctioning.

No, its still not fixed. Go to "Key Information.lua" and change "Keystone: " to "Schlüsselstein: "

Also, I kinda hate addons that force a certain language. I might play with a German client, yes, but that does not mean the German translation for addons is useful at all.

**Comment by CDAGaming** [comment]
Today we learned what happens when you don't properly test your code, and bundle it with support for a new extension.

**Comment by sinfonianartist** [comment]
> > Oh - is there any info if keystone responses are fixed for German clients?
> > Hasn't worked yet and guild members use ElvUI/WeakAura/etc. to post saved info as AstralKeys is malfunctioning.
> 
> No, its still not fixed. Go to "Key Information.lua" and change "Keystone: " to "Schlüsselstein: "
> 
> Also, I kinda hate addons that force a certain language. I might play with a German client, yes, but that does not mean the German translation for addons is useful at all.

This can be a feature request so that you can pick a certain language. Currently outside my scope. Also with the text coming from within a certain file, it means the original developer did not adhere to using a strings constants. I'm sure that will not be the only place it is misused.

**Comment by sinfonianartist** [comment]
> Today we learned what happens when you don't properly test your code, and bundle it with support for a new extension.

This is incorrect but thank you for your feedback. It is appreciated.

**Comment by CDAGaming** [comment]
> > Today we learned what happens when you don't properly test your code, and bundle it with support for a new extension.
> 
> This is incorrect but thank you for your feedback. It is appreciated.

![image](https://user-images.githubusercontent.com/16328918/110829779-1ec9a400-825e-11eb-83f8-93953ac77d95.png)

Proof of precisely what I said. Same update had both the toc update and the translations that were untested. If the addon crashes on launch, ie tested, it would have been found.

**Comment by sinfonianartist** [comment]
I tested this all last night and perhaps forgot to testv the German localizations. That's called software development. It's an iterative process. No need to flame here, it was broken for less than twelve hours. 

Feel free to contribute to the repository if you feel so inclined. Otherwise, realize that this is done as maintenance and not everything will be caught. 

If that is not something you wish to do, please keep it civilized and be constructive.

If you are unable to do so, please remove yourself before that happens forcefully.

Thank you.

**Comment by AmonFlorian** [comment]
Oh, oh. I didn't mean to start a fight here.
As this is completely open-source and free-to-use I don't get what reason there is to attack sinfonianartist.
I know the hard work involved in developing not-so-big tools. And I am overly grateful that people develop and share stuff with the world for free (!).
If there is anything I can help testing, sinfonianartist - please feel free to contact me (especially concerning German environments and such). And keep up the good work. :)

**Comment by CDAGaming** [comment]
> I tested this all last night and perhaps forgot to testv the German localizations. That's called software development. It's an iterative process. No need to flame here, it was broken for less than twelve hours.
> 
> Feel free to contribute to the repository if you feel so inclined. Otherwise, realize that this is done as maintenance and not everything will be caught.
> 
> If that is not something you wish to do, please keep it civilized and be constructive.
> 
> If you are unable to do so, please remove yourself before that happens forcefully.
> 
> Thank you.

I have been constructive throughout this discussion, part of the reason I dug into where this started at. As a developer as well, I understand the process.

As for forgetting to test the localization, the issue itself was occurring for those who were not even running the German localization (It occurred when the file was loaded, which is why I'm here discussing it.)

It is not my intent to flame you on this, merely to point out the facts to hopefully prevent such an issue from happening in the future. The last thing I'd want is to have such an issue like this occur but with a more major patch like 9.1/9.2. I apologize if you or anyone else has taken this the wrong way, but my intent was merely to inform.

**Comment by AmonFlorian** [comment]
@CDAGaming I could run the addon without any problem even with the faulty code. Only problems that occured were missing strings and fallback strings to English language. I wonder that it would crash for you.
Maybe it's the tone of your comments that helped to see you being rude - and I have to backup sinfonian that it was more ranting than helping to fix anything.

**Comment by CDAGaming** [comment]
@AmonFlorian Ah, then in that case, I'm not sure why the file was trying to load in that case, as my locale has always been under english (or whatever Blizzard sets as the defaults for US). Might look into that to see what could be loading it.

Again, I do apologize for the way my tone got conveyed, as I was only mainly trying to communicate my findings, developer-to-developer style. Everyone makes mistakes, and at this point I'm just hitting a dead stick at this point since the issue was already fixed.

**Comment by sinfonianartist** [comment]
> > I tested this all last night and perhaps forgot to testv the German localizations. That's called software development. It's an iterative process. No need to flame here, it was broken for less than twelve hours.
> > Feel free to contribute to the repository if you feel so inclined. Otherwise, realize that this is done as maintenance and not everything will be caught.
> > If that is not something you wish to do, please keep it civilized and be constructive.
> > If you are unable to do so, please remove yourself before that happens forcefully.
> > Thank you.
> 
> I have been constructive throughout this discussion, part of the reason I dug into where this started at.
> As a developer as well, I understand the process, and am grateful for you and others maintaining this addon.
> 
> As for testing the localization, the issue itself was occurring for those who were not even running the German localization (It occurred when the file was loaded even if the locale wasn't in use, which is why I'm here discussing it.). That's mainly why I'm in such a fiddle over this, as if the issue only effected a subset of the addon's audience, I wouldn't be giving it this much attention.
> 
> It was not my intent to flame you on this, merely to point out all the facts to hopefully prevent such an issue from happening in the future. The last thing I'd want is to have such an issue like this occur but with a more major patch like 9.1/9.2 (Where everyone would be in a hurry to update their addons).
> 
> I apologize if you or anyone else has taken this the wrong way, but my intent was merely to inform and not to start any sort of conflict.

I appreciate it. I am a mobile engineer by trade and not really a guru in terms of LUA. I've got a good dev environment setup but I'm not used to doing QA for other languages for this game, etc. I'm attempting to understand it as I go through and the testing can be a bit monotonous as game re-launches are required and I have to put myself in certain scenarios (ex. I will be running keys tonight without a guild tag to ascertain the underlying issue people are seeing without a guild tag).

I overlooked the issue with the Localization and that's definitely my fault. The fact that they were translated poorly, I would have had no idea. I thank you @AmonFlorian for giving us the better translations. I'm also noticing that with certain languages like German, it does not function well, as the UI was really built with the intent of being English only in its' layout and design.

I will be doing what I can over the coming weeks and months, and progress may be slow but I will do my best to ensure the main issues are corrected and potentially new features are added as I begin to understand more of the language and the inner workings of addon writing for World of Warcraft.

**Comment by CDAGaming** [comment]
If it helps, the error was caught within BugGrabber, but I didn't test it to see if the same error gets caught without it, so perhaps it was BugGrabber loading it somehow. I'll try and see later on.

I too am still very new to Lua (Porting over one of my Minecraft mods into Lua is not as easy as originally thought, but getting there), so I totally get where your coming from on this (Especially when finding edge-cases, like one specific area in Sanguine Depths not immediately giving a map id, and so on).

Either way, I'm glad we could smooth things over, and I'll see what I can do later tonight on behalf of whether it catches as a plain lua error or only in BugGrabber :)

**Comment by sinfonianartist** [comment]
Yeah the blank screen issue was the fact that the German strings were broken but the English ones were fine (causing the blank lua screen where the addon is messed up but not affecting your ability to play since it wasn't accessing the strings it was only loading it into memory)

**Comment by CDAGaming** [comment]
Ah I see, as when I checked in BugGrabber before, the error title came through fine, but the full stacktrace failed to show after the first reload oddly enough. That one was on me, since at the time, I assumed the issue was more severe then it actually was, so my bad for that one.
