### ISSUE TITLE
Incorrect Keys Listed

### ISSUE THREAD

**Issue by TerraDK** [astralguild/AstralKeys#3]
Currently there is a bug(?) where some people's keys are incorrectly listed. While you can fix this by relogging, you can also fix this by clicking "Friends" tab and back to "Guild" tab which will update to correct keys.

**Comment by tsitra** [comment]
Is this related to #17 and #10  ?

**Comment by TerraDK** [comment]
I forgot to close this but we actually tried to change method and frequency of clients communicating/update a while back. There's always going to be initial update needing to happen on log in but should correct itself quickly.
