### ISSUE TITLE
BAD TEXT "ANNOUNCE_NEW_KEY" 

### ISSUE THREAD

**Issue by Cellcubed** [astralguild/AstralKeys#35]
At the end of a mythic+ instead of announcing my new key, this text is sent to party chat instead: 

BAD TEXT "ANNOUNCE_NEW_KEY"

I have tried deleting the addon and the  wtf files and reinstalling. That didn't fix it.

**Comment by TerraDK** [comment]
Fixed in latest  update, ty.
