### ISSUE TITLE
Great Vault Feature

### ISSUE THREAD

**Issue by TerraDK** [astralguild/AstralKeys#5]
Two ideas for features:

1) Great Vault button. Currently you can open this in game without being at the vault by typing in this command `/run LoadAddOn("Blizzard_WeeklyRewards"); WeeklyRewardsFrame:Show()`. Perhaps we can take advantage of this?

2) Either as another option or in conjunction with above, perhaps we can add what Keys players have done listed in order so they know what they need or have done for the vault. Maybe to the right of player name or under best weekly on left side.

**Comment by sinfonianartist** [comment]
Added in 3.39
