### ISSUE TITLE
Latest build on the stable channel on Wago is incompatible with 9.2.7

### ISSUE THREAD

**Issue by mdavidson37** [astralguild/AstralKeys#57]
The latest version of Astral keys on the stable channel on Wago generates a huge (approx 500 per minute) number of errors when installed on 9.2.7. Rolling back to the previous release version fixes the issue.

Based on the version number: 3.60-dragonflight-beta I'm guessing this wasn't intended to be added to the stable channel.

**Comment by Khazakdk** [comment]
@mdavidson37 If you update from latest on the stable channel it should be back to normal now, let me know if it isn't.

**Comment by mdavidson37** [comment]
@Khazakdk Thanks - it' all good with the latest update!
