### ISSUE TITLE
Possible Tooltip Handler Error

### ISSUE THREAD

**Issue by lsuarez5280** [astralguild/AstralKeys#61]
It's not entirely clear which addon is responsible for this, but I'm guessing a tooltip handler from AstralKeys is responsible for an errant assumption it's handling a character tooltip, producing the following stack (as is probably evident, a tooltip is being rendered by HandyNotes' BfA plugin). It's consistently reproducible for rare mob tooltips from that addon plugin. Doesn't seem to be happening in HandyNotes Shadowlands or for BfA treasure tooltips.

> Message: Interface/AddOns/AstralKeys/Lists/Friends.lua:659: attempt to call method 'GetUnit' (a nil value)
> Time: Fri Nov 25 15:42:03 2022
> Count: 1
> Stack: Interface/AddOns/AstralKeys/Lists/Friends.lua:659: attempt to call method 'GetUnit' (a nil value)
> [string "@Interface/AddOns/AstralKeys/Lists/Friends.lua"]:659: in function <Interface/AddOns/AstralKeys/Lists/Friends.lua:656>
> [string "=(tail call)"]: ?
> [string "=[C]"]: in function \`securecallfunction'
> [string "@Interface/SharedXML/Tooltip/TooltipDataHandler.lua"]:60: in function <Interface/SharedXML/Tooltip/TooltipDataHandler.lua:55>
> [string "@Interface/SharedXML/Tooltip/TooltipDataHandler.lua"]:80: in function <Interface/SharedXML/Tooltip/TooltipDataHandler.lua:76>
> [string "@Interface/SharedXML/Tooltip/TooltipDataHandler.lua"]:116: in function <Interface/SharedXML/Tooltip/TooltipDataHandler.lua:106>
> [string "=[C]"]: in function \`SetAttribute'
> [string "@Interface/SharedXML/Tooltip/TooltipDataHandler.lua"]:141: in function <Interface/SharedXML/Tooltip/TooltipDataHandler.lua:134>
> [string "@Interface/SharedXML/Tooltip/TooltipDataHandler.lua"]:282: in function <Interface/SharedXML/Tooltip/TooltipDataHandler.lua:240>
> [string "=[C]"]: in function \`securecallfunction'
> [string "@Interface/SharedXML/Tooltip/TooltipDataHandler.lua"]:237: in function <Interface/SharedXML/Tooltip/TooltipDataHandler.lua:236>
> [string "=(tail call)"]: ?
> [string "@Interface/AddOns/HandyNotes_BattleForAzerothTreasures/handler/handler.lua"]:908: in function <...yNotes_BattleForAzerothTreasures/handler/handler.lua:743>
> [string "=(tail call)"]: ?
> [string "@Interface/AddOns/HandyNotes_BattleForAzerothTreasures/handler/handler.lua"]:949: in function <...yNotes_BattleForAzerothTreasures/handler/handler.lua:925>
> [string "=[C]"]: ?
> [string "@Interface/AddOns/HandyNotes/HandyNotes.lua"]:56: in function <Interface/AddOns/HandyNotes/HandyNotes.lua:51>
> [string "@Interface/AddOns/HandyNotes/HandyNotes.lua"]:166: in function `OnEnter'
> [string "@Interface/AddOns/HandyNotes/HandyNotes.lua"]:399: in function <Interface/AddOns/HandyNotes/HandyNotes.lua:398>

**Comment by Khazakdk** [comment]
Fixed with #75
