### ISSUE TITLE
AstralKeys/Affixes.lua:106: attempt to index field '?' (a nil value)

### ISSUE THREAD

**Issue by Rycia** [astralguild/AstralKeys#65]
245x AstralKeys/Affixes.lua:106: attempt to index field '?' (a nil value)
[string "@AstralKeys/Affixes.lua"]:106: in function `method'
[string "@AstralKeys/Events.lua"]:82: in function <AstralKeys/Events.lua:78>

Locals:
affixes = <table> {
}
(*temporary) = nil
(*temporary) = 1
(*temporary) = "Overflowing"
(*temporary) = "Healing in excess of a target's maximum health is instead converted to a heal absorption effect."
(*temporary) = 463570
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field '?' (a nil value)"
SEASON_AFFIX = 0
AffixOneID = 0
AffixTwoID = 0
AffixThreeID = 0
ROTATION_WEEK_POSITION = 0
GetRotationPosition = <function> defined @AstralKeys/Affixes.lua:85
addon = <table> {
 GetAffixID = <function> defined @AstralKeys/Affixes.lua:211
 SetPlayerNameRealm = <function> defined @AstralKeys/Character Info.lua:81
 Unit = <function> defined @AstralKeys/Unit Information.lua:22
 modules = <table> {
 }
 WeekTime = <function> defined @AstralKeys/AstralKeys.lua:14
 UnitClass = <function> defined @AstralKeys/Unit Information.lua:45
 AddUnitToList = <function> defined @AstralKeys/Lists/Lists.lua:93
 AddEscHandler = <function> defined @AstralKeys/Frame Functions.lua:250
 SetDefaultModulePrototype = <function> defined @Ace3/AceAddon-3.0/AceAddon-3.0.lua:405
 AffixThree = <function> defined @AstralKeys/Affixes.lua:159
 UpdateCharacterBest = <function> defined @AstralKeys/Key Information.lua:170
 SetUIScale = <function> defined @AstralKeys/Init.lua:5
 AffixTwo = <function> defined @AstralKeys/Affixes.lua:147
 IsEnabled = <function> defined @Ace3/AceAddon-3.0/AceAddon-3.0.lua:447
 GetCharacterKeyLevel = <function> defined @AstralKeys/Character Info.lua:131
 CreateDropDownFrame = <function> defined @AstralKeys/Frame Functions.lua:96
 WipeUnitList = <function> defined @AstralKeys/Unit Information.lua:39
 AffixOne = <function> defined @AstralKeys/Affixes.lua:134
 EXPANSION_LEVEL = 60
 SetEnabledState = <function> defined @Ace3/AceAddon-3.0/AceAddon-3.0.lua:420
 GetListFunction = <function> defined @AstralKeys/Lists.lua:24
 Week = 279
 UnitWeeklyBest = <function> defined @AstralKeys/Unit Information.lua:60
 DoesUnitBelongToList = <function> defined @AstralKeys/Lists/Lists.lua:131
 DataResetTime = <function> defined @AstralKeys/Settings.lua:6
 OnInitialize = <function> defined @AstralKeys/MinimapButton.lua:25
 NewModule = <function> defined @Ace3/AceAddon-3.0/AceAddon-3.0.lua:231
 AddListSort = <function> defined @AstralKeys/Tables.lua:177
 AddListFilter = <function> defined @AstralKeys/Tables.lua:170
 AstralToggle = <function> defined @AstralKeys/Frame.lua:1825
 GetName = <function> defined @Ace3/AceAddon-3.0/AceAddon-3.0.lua:275
 UpdateSortTable = <function> defined @AstralKeys/Frame.lua:1725
 RemoveUnitFromList = <function> defined @AstralKeys/Lists/Lists.lua:115
 WipeFriendList = <function> defined @AstralKeys/Lists/Friends.lua:88
 SetPlayerRealm = <function> defined @AstralKeys/Character Info.lua:92
 CreateKeyLink = <function> defined @AstralKeys/Key Information.lua:54
 Disable = <function> defined @Ace3/AceAddon-3.0/AceAddon-3.0.lua:310
 FindKeyStone = <function> defined @AstralKeys/Key Information.lua:110
 BNFriendUpdate = <function> defined @AstralKeys/Lists/Friends.lua:31
 Print = <function> defined @Ace3/AceConsole-3.0/AceConsole-3.0.lua:50
 L = <table> {
 }
 PushKeyDataToFriends = <function> defined @AstralKeys/Lists/Friends.lua:298
 GuildMemberOnline = <function> defined @AstralKeys/Lists/Guild.lua:27
 UpdateAffixes = <function> defined @AstralKeys/Frame.lua:1677
 CheckGuildVersion = <function> defined @Interface

**Comment by TreizeEU** [comment]
This issue still seems to be a thing with version 3.66? Although I'm not sure if it's due to my EU client still being pre-season 1 and that it will fix itself tomorrow?

**Comment by TreizeEU** [comment]
The lua error I'm currently getting:

`218x AstralKeys/Affixes.lua:106: attempt to index field '?' (a nil value)
[string "@AstralKeys/Affixes.lua"]:106: in function `method'
[string "@AstralKeys/Events.lua"]:82: in function <AstralKeys/Events.lua:78>

Locals:
affixes = <table> {
 1 = <table> {
 }
 2 = <table> {
 }
 3 = <table> {
 }
}
(*temporary) = nil
(*temporary) = 1
(*temporary) = "Overflowing"
(*temporary) = "Healing in excess of a target's maximum health is instead converted to a heal absorption effect."
(*temporary) = 463570
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field '?' (a nil value)"
SEASON_AFFIX = 0
AffixOneID = 0
AffixTwoID = 0
AffixThreeID = 0
ROTATION_WEEK_POSITION = 0
GetRotationPosition = <function> defined @AstralKeys/Affixes.lua:85
addon = <table> {
 GetAffixID = <function> defined @AstralKeys/Affixes.lua:211
 SetPlayerNameRealm = <function> defined @AstralKeys/Character Info.lua:81
 Unit = <function> defined @AstralKeys/Unit Information.lua:22
 modules = <table> {
 }
 WeekTime = <function> defined @AstralKeys/AstralKeys.lua:14
 UnitClass = <function> defined @AstralKeys/Unit Information.lua:45
 AddUnitToList = <function> defined @AstralKeys/Lists/Lists.lua:93
 AddEscHandler = <function> defined @AstralKeys/Frame Functions.lua:250
 SetDefaultModulePrototype = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:405
 AffixThree = <function> defined @AstralKeys/Affixes.lua:159
 UpdateCharacterBest = <function> defined @AstralKeys/Key Information.lua:170
 SetUIScale = <function> defined @AstralKeys/Init.lua:5
 AffixTwo = <function> defined @AstralKeys/Affixes.lua:147
 IsEnabled = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:447
 GetCharacterKeyLevel = <function> defined @AstralKeys/Character Info.lua:131
 CreateDropDownFrame = <function> defined @AstralKeys/Frame Functions.lua:96
 WipeUnitList = <function> defined @AstralKeys/Unit Information.lua:39
 AffixOne = <function> defined @AstralKeys/Affixes.lua:134
 EXPANSION_LEVEL = 60
 SetEnabledState = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:420
 GetListFunction = <function> defined @AstralKeys/Lists.lua:24
 Week = 279
 UnitWeeklyBest = <function> defined @AstralKeys/Unit Information.lua:60
 DoesUnitBelongToList = <function> defined @AstralKeys/Lists/Lists.lua:131
 DataResetTime = <function> defined @AstralKeys/Settings.lua:6
 OnInitialize = <function> defined @AstralKeys/MinimapButton.lua:25
 NewModule = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:231
 AddListSort = <function> defined @AstralKeys/Tables.lua:177
 AddListFilter = <function> defined @AstralKeys/Tables.lua:170
 AstralToggle = <function> defined @AstralKeys/Frame.lua:1825
 GetName = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:275
 UpdateSortTable = <function> defined @AstralKeys/Frame.lua:1725
 RemoveUnitFromList = <function> defined @AstralKeys/Lists/Lists.lua:115
 WipeFriendList = <function> defined @AstralKeys/Lists/Friends.lua:88
 SetPlayerRealm = <function> defined @AstralKeys/Character Info.lua:92
 CreateKeyLink = <function> defined @AstralKeys/Key Information.lua:54
 Disable = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:310
 FindKeyStone = <function> defined @AstralKeys/Key Information.lua:110
 BNFriendUpdate = <function> defined @AstralKeys/Lists/Friends.lua:31
 Print = <function> defined @DataStore/libs/AceConsole-3.0/AceConsole-3.0.lua:50
 L = <table> {
 }
 PushKeyDataToFriends = <function> defined @AstralKeys/Lists/Friends.lua:298
 GuildMemberOnline = <function> defined @AstralKeys/Lists/Guild.lua:27
 Updat`
