### ISSUE TITLE
"No key found" Bug

### ISSUE THREAD

**Issue by ruuuudyyyy** [astralguild/AstralKeys#7]
I've got the weird issue on my main character not getting any keystone information into astral keys.
On my alt it works perfectly fine.
After every dungeon it links my key into chat as a "new keystone" line but still doesnt show either on astral itself or doesnt respond at !keys. Constantly getting a Errors in my bugsack with this:

412x AstralKeys\Lists\Friends-Friends.lua:299: bad argument #3 to 'strformat' (string expected, got nil)
[string "=[C]"]: ?
[string "@AstralKeys\Lists\Friends-Friends.lua"]:299: in function <AstralKeys\Lists\Friends.lua:290>
[string "@AstralKeys\Lists\Friends-Friends.lua"]:384: in function `method'
[string "@AstralKeys\Communications.lua"]:82: in function <AstralKeys\Communications.lua:70>

Locals:
(*temporary) = "%s:%s:%d:%d:%d:%d:%d:%d"
(*temporary) = "Pokihmm-Draenor"
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = 180
(*temporary) = 378841
(*temporary) = 1
(*temporary) = 13
(*temporary) = "string expected, got nil"

I deleted the lua under saved variables serval times and reinstalled it. 
Started at Shadowlands release pretty much.
![Wow_JQqcTR6N7D](https://user-images.githubusercontent.com/77745731/105212223-78aac900-5b4d-11eb-8fc1-61db46e04e1c.png)

**Comment by Vortilion** [comment]
Same issue here.
