### ISSUE TITLE
[Feature Request] Respond in Communities

### ISSUE THREAD

**Issue by Wutname1** [astralguild/AstralKeys#70]
With the increase in cross faction activities our guild has grown over factions greatly and we use a community to facilitate chat, it would be great if Astral keys could respond to `!keys` commands in the Community.

**Comment by Khazakdk** [comment]
Unfortunately the communities feature is totally blocked off from addons.  I've looked into this before, and even after 10.0 there is still no way for addon authors to read communities chat.
