### ISSUE TITLE
Feature request: Character iLevel

### ISSUE THREAD

**Issue by SkrybeGH** [astralguild/AstralKeys#77]
Is there any possibility of storing the players ilevel in AstralCharacters{} and having an option to return it when announcing your keys to group/guild/friend? It'd make life easier when choosing which characters/keys to use if you could easily see what the characters ilevel was. "Has the key we want but will be a carry because of ilevel" essentially.

So when announcing it'd appear something like the following;

MyWarriorName (357.1) Keystone: Halls of Valor 2
MyDruidName (381) - Keystone: Ruby Life Pools 6

It's relatively easy to get the current player's ilevel using "playerILevel = GetAverageItemLevel()".

**Comment by Khazakdk** [comment]
This seems like something that can be easily done, should get it out in the next couple weeks.

**Comment by SkrybeGH** [comment]
That's excellent. Thanks.

If I can provide any assistance in testing I'm definitely happy to do so.
