### ISSUE TITLE
Command report all the keys 

### ISSUE THREAD

**Issue by Therepup** [astralguild/AstralKeys#79]
Back in BFA I used to run a combination of addons and weakauras when someone used !keys It would respond with all the keys I had like  astralkeys do if you use the report button. Is there a way to make it automatic IF you want to do that kind of thing? I am an altoholic so I have a lot of toons and do keys with all of them

**Comment by TerraDK** [comment]
Are you trying to report all your keys? You can use the speaker icon on left side of Astral Keys and itll post all your characters' keys
